#!/bin/bash

### 行云API 卸载后回调
### wizard_delete_data="true"  → 删除全部数据

[ -z "${TRIM_PKGHOME}" ] && exit 0

if [ "${wizard_delete_data}" = "true" ]; then
    [ -n "${TRIM_PKGVAR}" ] && rm -rf "${TRIM_PKGVAR}" 2>/dev/null || true
    [ -n "${TRIM_PKGHOME}" ] && rm -rf "${TRIM_PKGHOME}" 2>/dev/null || true
fi

exit 0
